pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'docker run -v $PWD/UPF_Firewall:/UPF_Firewall logicalhacking:isabelle2018 isabelle build -D /UPF_Firewall'
            }
        }
    }
}
